visual_servoing:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/drive"
    side: -1
    velocity: 1.0
    desired_distance: 1.
    cone_dt: 0.1
    Kp_steer: 0.5
    Kd_steer: -0.1
    Kp_speed: 0.5
    Kd_speed: -0.1
